### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by Dejulia489** [mmajcica/win-rm-file-copy#10]
I sporadically get the following error when using this task. 

```
2019-06-21T15:27:25.7096529Z Files from 'D:\Agents\A1\_work\r1\a\Folder\Folder\*' will be copied to the path 'D:\\Folder\\Folder\\Folder\' on the remote machine(s).
2019-06-21T15:27:26.4590551Z Copy started for - myServer.myDomain
2019-06-21T15:28:27.1728117Z ##[error]An item with the same key has already been added.
```

Let me know what information you would like to help with troubleshooting.

**Comment by mmajcica** [comment]
If you run your build/release with the high verbosity, do you get any extra info in order where this error is reported? At what stage?
Seems that the same entry in some dictionary is being added twice. But where? :)

**Comment by Dejulia489** [comment]
I have added 'system.debug = true' to my pipelines, I will report back once I experience the error with the logs. Let me know if you would like me to enable any other logging. 

Thanks

**Comment by Dejulia489** [comment]
It finally happened again, please see below for a copy of the redacted log...

`2019-07-02T15:26:23.8426549Z ##[debug]Evaluating condition for step: 'Copy files'
2019-07-02T15:26:23.8427255Z ##[debug]Evaluating: succeeded()
2019-07-02T15:26:23.8427444Z ##[debug]Evaluating succeeded:
2019-07-02T15:26:23.8427755Z ##[debug]=> True
2019-07-02T15:26:23.8428078Z ##[debug]Result: True
2019-07-02T15:26:23.8428362Z ##[section]Starting: Copy files
2019-07-02T15:26:23.8679246Z ==============================================================================
2019-07-02T15:26:23.8679421Z Task         : Windows Machine File Copy (WinRM)
2019-07-02T15:26:23.8679523Z Description  : Copy files on remote machines via WinRM
2019-07-02T15:26:23.8679629Z Version      : 2.0.7
2019-07-02T15:26:23.8679713Z Author       : Mario Majcica
2019-07-02T15:26:23.8679838Z Help         : Replace with markdown to show in help
2019-07-02T15:26:23.8679963Z ==============================================================================
2019-07-02T15:26:27.6081627Z ##[debug]VstsTaskSdk 0.8.2 commit 
2019-07-02T15:26:28.0866905Z ##[debug]Entering D:\A3\_work\_tasks\WinRmFileCopy_08ccbc90-a50e-11e7-b6d4-73125b89d3af\2.0.7\WinRmFileCopy.ps1.
2019-07-02T15:26:28.0867356Z ##[debug]INPUT_MACHINENAMES: ********
2019-07-02T15:26:28.0867591Z ##[debug]INPUT_ADMINUSERNAME: ********
2019-07-02T15:26:28.2373328Z ##[debug]INPUT_ADMINPASSWORD: '***'
2019-07-02T15:26:28.2578469Z ##[debug]INPUT_SOURCEPATH: 'D:\A3\_work\r53\a\_****\****'
2019-07-02T15:26:28.2914705Z ##[debug]INPUT_TARGETPATH: 'D:\temp\****'
2019-07-02T15:26:28.3505484Z ##[debug]INPUT_CLEANTARGETBEFORECOPY: 'true'
2019-07-02T15:26:28.3601418Z ##[debug] Converted to bool: True
2019-07-02T15:26:28.3707479Z ##[debug]INPUT_COPYFILESINPARALLEL: 'false'
2019-07-02T15:26:28.3708131Z ##[debug] Converted to bool: False
2019-07-02T15:26:28.3708526Z ##[debug]INPUT_USESSL: 'false'
2019-07-02T15:26:28.3708897Z ##[debug] Converted to bool: False
2019-07-02T15:26:28.3709360Z ##[debug]INPUT_TESTCERTIFICATE: 'false'
2019-07-02T15:26:28.3709895Z ##[debug] Converted to bool: False
2019-07-02T15:26:28.3710274Z ##[debug]SYSTEM_DEBUG: 'true'
2019-07-02T15:26:28.3710619Z ##[debug] Converted to bool: True
2019-07-02T15:26:28.3710949Z Files from 'D:\A3\_work\r53\a\_****\****\*' will be copied to the path 'D:\temp\****\' on the remote machine(s).
2019-07-02T15:26:28.9777343Z ##[debug]Invoked Resolve-HostNameOrAddress with ComputerName = 'FullyQualified_ComputerName'
2019-07-02T15:26:29.0783048Z Copy started for - FullyQualified_ComputerName
2019-07-02T15:26:31.4149733Z ##[debug]Performing the operation "Copy Directory" on target "Item: D:\A3\_work\r53\a\_****\****\bin Destination: D:\temp\****\bin".
2019-07-02T15:26:35.1891183Z ##[debug]Performing the operation "Copy File" on target "Item: D:\A3\_work\r53\a\_****\****\bin\myprogram.dll Destination: D:\temp\****\bin".
2019-07-02T15:26:35.9777081Z ##[debug]Performing the operation "Copy File" on target "Item: D:\A3\_work\r53\a\_****\****\bin\myprogram.pdb Destination: D:\temp\****\bin".
2019-07-02T15:26:36.4230261Z ##[debug]Error record:
2019-07-02T15:26:36.5547933Z ##[debug]Copy-Item : An item with the same key has already been added.
2019-07-02T15:26:36.5597586Z ##[debug]At D:\A3\_work\_tasks\WinRmFileCopy_08ccbc90-a50e-11e7-b6d4-73125b89d3af\2.0.7\WinRmFileCopy.ps1:138 char:13
2019-07-02T15:26:36.5605322Z ##[debug]+             Copy-Item -Path $sourcePath -Destination $targetPath -For ...
2019-07-02T15:26:36.5606039Z ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-07-02T15:26:36.5608899Z ##[debug]    + CategoryInfo          : InvalidOperation: (System.Management.Automation.    PowerShell:PowerShell) [Copy-Item], ArgumentException
2019-07-02T15:26:36.5620455Z ##[debug]    + FullyQualifiedErrorId : CopyFileRemoteExecutionError,Microsoft.PowerShel    l.Commands.CopyItemCommand
2019-07-02T15:26:36.5765082Z ##[debug] 
2019-07-02T15:26:36.5769099Z ##[debug]Script stack trace:
2019-07-02T15:26:36.5769523Z ##[debug]at <ScriptBlock>, D:\A3\_work\_tasks\WinRmFileCopy_08ccbc90-a50e-11e7-b6d4-73125b89d3af\2.0.7\WinRmFileCopy.ps1: line 138
2019-07-02T15:26:36.5769804Z ##[debug]at <ScriptBlock>, D:\A3\_work\_tasks\WinRmFileCopy_08ccbc90-a50e-11e7-b6d4-73125b89d3af\2.0.7\WinRmFileCopy.ps1: line 171
2019-07-02T15:26:36.5770035Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-07-02T15:26:36.5770202Z ##[debug]at <ScriptBlock>, <No file>: line 22
2019-07-02T15:26:36.5770411Z ##[debug]at <ScriptBlock>, <No file>: line 18
2019-07-02T15:26:36.5770737Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-07-02T15:26:36.5778334Z ##[debug]Exception:
2019-07-02T15:26:36.5889900Z ##[debug]System.ArgumentException: An item with the same key has already been added.
2019-07-02T15:26:36.5901991Z ##[debug]   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
2019-07-02T15:26:36.5915075Z ##[debug]   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
2019-07-02T15:26:36.5927447Z ##[debug]   at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler.CreatePowerShellOnServerAndInvoke(ClientRemotePowerShell shell)
2019-07-02T15:26:36.5939898Z ##[debug]   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.CreatePowerShellOnServerAndInvoke(ClientRemotePowerShell shell)
2019-07-02T15:26:36.5952383Z ##[debug]   at System.Management.Automation.PowerShell.CoreInvokeAsync[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings, AsyncCallback callback, Object state, PSDataCollection`1 asyncResultOutput)
2019-07-02T15:26:36.5964773Z ##[debug]   at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2019-07-02T15:26:36.5977148Z ##[debug]   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2019-07-02T15:26:36.5989471Z ##[debug]   at System.Management.Automation.PowerShell.Invoke[T]()
2019-07-02T15:26:36.6005213Z ##[debug]   at Microsoft.PowerShell.Commands.SafeInvokeCommand.Invoke(PowerShell ps, FileSystemProvider fileSystemContext, CmdletProviderContext cmdletContext, Boolean shouldHaveOutput)
2019-07-02T15:26:36.6342224Z ##[error]An item with the same key has already been added.`

**Comment by aczarkowski** [comment]
It works now. Thanks for fixing it so quickly.

**Comment by marianielias** [comment]
@mmajcica 
Hi, I'm having the same problem with Copy-Item using PSSessions on some scripts, Google only brings me here. xD
Did you find what generates the "Copy-Item : An item with the same key has already been added." error?

Cheers.

**Comment by Dejulia489** [comment]
@FlingeR 
I did not, I ended up writing my own script that zipped the package, copied it to the target and then expanded the package. I saw some speed improvements with this approach when copying to multiple targets.
